Try building Ubuntu JARs with older glibc. (#55)
* Pin dockcross version.

* Add explicit error messages when glibc minimum versions are not met.

diff --git a/.github/workflows/all.yml b/.github/workflows/all.yml
--- a/.github/workflows/all.yml
+++ b/.github/workflows/all.yml
@@ -318,15 +318,15 @@ jobs:
           echo "Checking mac-aarch64/libvoyager.dylib for arm64 architecture..."
           file combined-jar/mac-aarch64/libvoyager.dylib | grep arm64
 
-          # Check the Linux JARs to ensure a sufficiently old required GLIBC and GLIBCXX version:
+          echo "Checking the Linux JARs to ensure a sufficiently old required GLIBC and GLIBCXX version in each..."
           echo "Checking linux-aarch64/libvoyager.so for GLIBC 2.27..."
-          objdump -T combined-jar/linux-aarch64/libvoyager.so | grep GLIBC | sed 's/.*GLIBC_\([.0-9]*\).*/\1/g' | sort -Vu | tail -n 1 | grep 2\.27
+          objdump -T combined-jar/linux-aarch64/libvoyager.so | grep GLIBC | sed 's/.*GLIBC_\([.0-9]*\).*/\1/g' | sort -Vu | tail -n 1 | grep 2\.27 || echo "Expected linux-aarch64 binary to require at most glibc 2.27. Ensure the dockcross container has not been updated." && false
           echo "Checking linux-aarch64/libvoyager.so for GLIBCXX 3.4.22..."
-          objdump -T combined-jar/linux-aarch64/libvoyager.so | grep GLIBCXX | sed 's/.*GLIBCXX_\([.0-9]*\).*/\1/g' | sort -Vu | tail -n 1 | grep 3\.4\.22
+          objdump -T combined-jar/linux-aarch64/libvoyager.so | grep GLIBCXX | sed 's/.*GLIBCXX_\([.0-9]*\).*/\1/g' | sort -Vu | tail -n 1 | grep 3\.4\.22 || echo "Expected linux-aarch64 binary to require at most glibc++ 3.4.22. Ensure the dockcross container has not been updated." && false
           echo "Checking linux-x64/libvoyager.so for GLIBC 2.29..."
-          objdump -T combined-jar/linux-x64/libvoyager.so | grep GLIBC | sed 's/.*GLIBC_\([.0-9]*\).*/\1/g' | sort -Vu | tail -n 1 | grep 2\.29
+          objdump -T combined-jar/linux-x64/libvoyager.so | grep GLIBC | sed 's/.*GLIBC_\([.0-9]*\).*/\1/g' | sort -Vu | tail -n 1 | grep 2\.29 || echo "Expected linux-x64 binary to require at most glibc 2.29. Ensure the dockcross container has not been updated." && false
           echo "Checking linux-x64/libvoyager.so for GLIBCXX 3.4.22..."
-          objdump -T combined-jar/linux-x64/libvoyager.so | grep GLIBCXX | sed 's/.*GLIBCXX_\([.0-9]*\).*/\1/g' | sort -Vu | tail -n 1 | grep 3\.4\.22
+          objdump -T combined-jar/linux-x64/libvoyager.so | grep GLIBCXX | sed 's/.*GLIBCXX_\([.0-9]*\).*/\1/g' | sort -Vu | tail -n 1 | grep 3\.4\.22  || echo "Expected linux-x64 binary to require at most glibc++ 3.4.22. Ensure the dockcross container has not been updated." && false
 
           zip -r $(ls java-* | grep jar | tail -n 1) combined-jar/*
       - uses: actions/upload-artifact@v3
